---
- name: install wget openjdk
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - wget
      - openjdk-8-jdk
      - apt-transport-https

- name: Create a group zookeeper
  group:
    name: "{{ sansible_zookeeper_user }}"
    state: present

- name: Create an user zookeeper
  user:
    name: "{{ sansible_zookeeper_user }}"
    group: "{{ sansible_zookeeper_group }}"
    state: present
    shell: /bin/bash

- name: Create Zookeeper directories
  file:
    group: "{{ sansible_zookeeper_group }}"
    owner: "{{ sansible_zookeeper_user }}"
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sansible_zookeeper_home_dir }}"
    - "{{ sansible_zookeeper_home_dir }}/scripts"
    - "{{ sansible_zookeeper_install_dir }}"
    - "{{ sansible_zookeeper_conf_dir }}"
    - "{{ sansible_zookeeper_data_dir }}"
    - "{{ sansible_zookeeper_log_dir }}"

- name: Download ZooKeeper
  get_url:
    url: "{{ sansible_zookeeper_download_url }}"
    dest: "{{ sansible_zookeeper_home_dir }}/zookeeper-{{ sansible_zookeeper_version }}.tar.gz"

- name: Unpack Zookeeper
  unarchive:
    copy: no
    creates: "{{ sansible_zookeeper_home_dir }}/zookeeper-{{ sansible_zookeeper_version }}"
    dest: "{{ sansible_zookeeper_home_dir }}"
    src: "{{ sansible_zookeeper_home_dir }}/zookeeper-{{ sansible_zookeeper_version }}.tar.gz"

- name: Change directories owner
  file:
    path: "{{ sansible_zookeeper_home_dir }}"
    group: "{{ sansible_zookeeper_group }}"
    owner: "{{ sansible_zookeeper_user }}"
    recurse: yes

- name: Link to Zookeeper Directory
  file:
    dest: "{{ sansible_zookeeper_install_dir }}/zookeeper"
    src: "{{ sansible_zookeeper_home_dir }}/zookeeper-{{ sansible_zookeeper_version }}"
    state: link

- name: Create Zookeeper service
  become: yes
  template:
    dest: /etc/init.d/zookeeper
    mode: 0755
    owner: root
    src: zookeeper_sysv.j2

- name: Create zookeeper startup links
  become: yes
  command: update-rc.d zookeeper defaults
  args:
    creates: "/etc/rc0.d/K??zookeeper"
  when: ansible_distribution_release == "bionic"
