---
- name: install wget openjdk
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - wget
      - openjdk-8-jdk

- name: Create an user zookeeper
  user:
    name: "{{ sansible_zookeeper_user }}"
    group: "{{ sansible_zookeeper_group }}"
    state: present
    shell: /bin/bash

- name: Create Zookeeper directories
  become: yes
  file:
    group: "{{ sansible_zookeeper_group }}"
    owner: "{{ sansible_zookeeper_user }}"
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sansible_zookeeper_home_dir }}"
    - "{{ sansible_zookeeper_home_dir }}/scripts"
    - "{{ sansible_zookeeper_install_dir }}"
    - "{{ sansible_zookeeper_conf_dir }}"
    - "{{ sansible_zookeeper_data_dir }}"
    - "{{ sansible_zookeeper_log_dir }}"

- name: Download and Unpack Zookeeper
  become: yes
  become_user: "{{ sansible_zookeeper_user }}"
  unarchive:
    dest: "{{ sansible_zookeeper_home_dir }}"
    src: "{{ sansible_zookeeper_download_url }}"
    remote_src: true
  args:
    creates: "{{ sansible_zookeeper_home_dir }}/zookeeper-{{ sansible_zookeeper_version }}"

- name: Link to Zookeeper Directory
  become: yes
  become_user: "{{ sansible_zookeeper_user }}"
  file:
    dest: "{{ sansible_zookeeper_install_dir }}"
    src: "{{ sansible_zookeeper_home_dir }}/zookeeper-{{ sansible_zookeeper_version }}"
    state: link

- name: Create Zookeeper service
  become: yes
  template:
    dest: /etc/init.d/zookeeper
    mode: 0755
    owner: root
    src: zookeeper_sysv.j2

- name: Create zookeeper startup links
  become: yes
  command: update-rc.d zookeeper defaults
  args:
    creates: "/etc/rc0.d/K??zookeeper"
  when: ansible_distribution_release == "bionic"
