---

- name: Setup Zookeeper environment config
  become: yes
  become_user: "{{ sansible_zookeeper_user }}"
  template:
    dest: "{{ sansible_zookeeper_conf_dir }}/environment"
    mode: 0644
    src: environment.j2
  notify:
    - restart zookeeper

- name: Setup myid
  become: yes
  become_user: "{{ sansible_zookeeper_user }}"
  template:
    dest: "{{ sansible_zookeeper_data_dir }}/myid"
    src: myid.j2
  notify:
    - restart zookeeper

- name: Setup zoo.cfg file
  become: yes
  become_user: "{{ sansible_zookeeper_user }}"
  template:
    dest: "{{ sansible_zookeeper_conf_dir }}/zoo.cfg"
    mode: 0644
    src: zoo.cfg.j2
  notify:
    - restart zookeeper

- name: Create Zookeeper log4j config
  become: yes
  become_user: "{{ sansible_zookeeper_user }}"
  template:
    dest: "{{ sansible_zookeeper_conf_dir }}/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart zookeeper

- name: Start Zookeeper service
  become: yes
  service:
    enabled: yes
    name: zookeeper
    state: started

- name: Wait for Zookeeper client port
  wait_for:
    port: "{{ sansible_zookeeper_client_port }}"
    state: started
    timeout: 60

- name: Copy zookeeper check script
  become: yes
  become_user: "{{ sansible_zookeeper_user }}"
  copy:
    src: zookeeper_check
    dest: "{{ sansible_zookeeper_home_dir }}/scripts/zookeeper_check"
    owner: "{{ sansible_zookeeper_user }}"
    group: "{{ sansible_zookeeper_group }}"
    mode: 0750
