---
- name: Set Zookeeper Id
  set_fact: zookeeper_id={{item.0 + 1}}
  with_indexed_items: "{{ groups['zookeeper-nodes'] }}"
  when: item.1 == "{{inventory_hostname}}"

- name: Setup Zookeeper environment config
  template:
    dest: "{{ sansible_zookeeper_conf_dir }}/environment"
    mode: 0644
    src: environment.j2
  notify:
    - restart zookeeper

- name: Setup myid
  template:
    dest: "{{ sansible_zookeeper_data_dir }}/myid"
    src: myid.j2
  notify:
    - restart zookeeper

- name: Setup zoo.cfg file
  template:
    dest: "{{ sansible_zookeeper_conf_dir }}/zoo.cfg"
    mode: 0644
    src: zoo.cfg.j2
  notify:
    - restart zookeeper

- name: Create Zookeeper log4j config
  template:
    dest: "{{ sansible_zookeeper_conf_dir }}/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart zookeeper

- name: Start Zookeeper service
  become: yes
  service:
    enabled: yes
    name: zookeeper
    state: started
    daemon_reload: yes

- name: Wait for Zookeeper client port
  wait_for:
    port: "{{ sansible_zookeeper_client_port }}"
    state: started
    timeout: 60

- name: Copy zookeeper check script
  copy:
    src: zookeeper_check
    dest: "{{ sansible_zookeeper_home_dir }}/scripts/zookeeper_check"
    owner: "{{ sansible_zookeeper_user }}"
    group: "{{ sansible_zookeeper_group }}"
    mode: 0750

- name: Change directories owner
  file:
    path: "{{ sansible_zookeeper_home_dir }}"
    group: "{{ sansible_zookeeper_group }}"
    owner: "{{ sansible_zookeeper_user }}"
    recurse: yes
